### PR TITLE
Swagger data model

### PR DESCRIPTION
**Pull request by zhengtr**
- Add `flask-restx` in dependencies, including `requirements.txt`
- Add `flask_restx.Api` in `service/__init__.py`
- Add create_model, inventory_model, and reqparse in `routes.py`

The api docs can be accessed and checked in `{base_url}/apidocs`
**Please remember to delete previous docker volume and rebuild the container before checking.**

### CODE REVIEW

**Comment by zhengtr** [comment]
> @zhengtr everything seems to be working as expected but I can't see any of the models on the /apicdocs page. Will they only appear after the endpoints are refactored to use flask-restx?

Yes. I think they will only appear after the resource class is implemented (i.e. refactored endpoints). I will take an issue and working on the endpoint after this PR.

**Review by sahildeshpande25 — APPROVED** [review]
Everything looks good. API prefix added to all endpoints. BASE URL will have to be updated when testing later on.

**Comment by shradhaiyer** [comment]
Also, you may have to rebase with master. I just approved Sahil's PR

**Comment by rachitjain2706** [comment]
> Also, you may have to rebase with master. I just approved Sahil's PR

Since the changes were in different files, you can rebase and merge it through GitHub directly. You can click on the dropdown in the `Merge Pull Request` option.

**Review by shradhaiyer — APPROVED** [review]

**Comment by rachitjain2706** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/15332261-faa1-4111-91e5-bb4a4e7761cb?env_id=ibm:yp:us-south "nyu-inventory"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/0ee75414-6b60-4df5-9cdb-fdf2afb5159e "inventory") deployed [inventory](https://github.com/CSCI-GA-2820-SP23-003/inventory/releases/tag/deploy-inventory-20230427-154421 "deploy-inventory-20230427-154421") to [inventory](https://cloud.ibm.com/kubernetes/clusters/cgiqshuf0vsnk546pts0/overview "There was a problem retrieving the space name"), including commit 31084b233f8edcf501ed4ec1b5593508d868f0a7

**Pull request merged**
