### PR TITLE
Added Query for Items that need Restocking

### PR DESCRIPTION
**Pull request by sahildeshpande25**
- added query to list items that need to or don't need to be restocked
- updated value range for `restock_level` in `factories.py`

### CODE REVIEW

**Review by rachitjain2706 — APPROVED** [review]
LGTM

**Review by zhengtr — APPROVED** [review]
LGTM

**Comment by zhengtr** [comment]
Hi @sahildeshpande25, I just approved this PR but I found out that with current implementation, if I send a GET request `http://127.0.0.1:8000/inventory?restock=`, our app will list all items in the db. I will confirm with professor about what should the expected response be. If this needs to be changed, I will open a new bug report. I will keep you updated.

**Comment by zhengtr** [comment]
> Hi @sahildeshpande25, even though I just approved this PR, I found out that with current implementation, if I send a GET request `http://127.0.0.1:8000/inventory?restock=`, our app will list all items in the db. I will confirm with professor about what should the expected response be. If this needs to be changed, I will open a new bug report. I will keep you updated.

Your implementation is correct! No need to change.

**Pull request merged**
